name: Build Test Packages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'research/packaging_requests/used_during_implementation.csv'
      - 'src/**'
      - '.github/workflows/train-on-dataset.yml'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Nix
        uses: cachix/install-nix-action@v24
        
      - name: Cache Nix store
        uses: actions/cache@v4
        with:
          path: /nix
          key: nix-${{ runner.os }}-${{ hashFiles('flake.lock') }}
          restore-keys: |
            nix-${{ runner.os }}-
        
      - name: Create packagerix config
        run: |
          mkdir -p ~/.packagerix
          cat > ~/.packagerix/config.json << EOF
          {
            "provider": "anthropic",
            "model": "claude-3-5-haiku-20241022",
            "backend": "litellm"
          }
          EOF
          
      - name: Cache packagerix config
        uses: actions/cache@v4
        with:
          path: ~/.packagerix
          key: packagerix-config-v1
        
      - name: Build packagerix environment
        run: |
          nix develop .# --command echo "Development environment ready"
        
      - name: Create matrix from CSV
        id: create-matrix
        run: |
          python3 -c "
          import csv
          import json
          
          matrix_data = []
          with open('research/packaging_requests/used_during_implementation.csv', 'r') as f:
              reader = csv.DictReader(f)
              for row in reader:
                  if row['repo_url']:  # Skip entries without repo URLs
                      matrix_data.append({
                          'issue_number': row['issue_number'],
                          'repo_url': row['repo_url']
                      })
          
          # GitHub Actions has a matrix size limit, so we might need to batch
          # Limit to first 5 entries for testing
          matrix = {'include': matrix_data[:5]}
          
          with open('matrix.json', 'w') as f:
              json.dump(matrix, f)
          
          # Set output for GitHub Actions
          print(f'matrix={json.dumps(matrix)}')
          "
          echo "matrix=$(cat matrix.json)" >> $GITHUB_OUTPUT

  build-test-packages:
    needs: setup
    runs-on: ubuntu-latest
    name: Package ${{ matrix.repo_url }}
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
      max-parallel: 5  # Limit concurrent jobs to avoid rate limiting
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Nix
        uses: cachix/install-nix-action@v24
        
      - name: Restore Nix cache
        uses: actions/cache@v4
        with:
          path: /nix
          key: nix-${{ runner.os }}-${{ hashFiles('flake.lock') }}
          restore-keys: |
            nix-${{ runner.os }}-
        
      - name: Restore packagerix config
        uses: actions/cache@v4
        with:
          path: ~/.packagerix
          key: packagerix-config-v1
          
      - name: Setup environment
        run: |
          # Set Anthropic API key as environment variable
          echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" >> $GITHUB_ENV
      
      - name: Process package request
        id: process
        run: |
          echo "Processing issue #${{ matrix.issue_number }} - ${{ matrix.repo_url }}"
          
          # Create output directory for this run
          mkdir -p output
          
          # Run packagerix with raw output and save results
          { nix develop .# -c python -m packagerix \
              --raw \
              --output-dir output \
              "${{ matrix.repo_url }}" \
              2>&1 | tee "${{ matrix.issue_number }}.log"; } \
            && exit_code=0 || exit_code=$?
          
          # Check if the command succeeded
          if [ $exit_code -eq 0 ]; then
            echo "status=success" >> $GITHUB_OUTPUT
            # Find the package name from the output directory
            if [ -d output ]; then
              package_name=$(ls output | head -n1)
              if [ -n "$package_name" ]; then
                echo "package_name=$package_name" >> $GITHUB_OUTPUT
              fi
            fi
          else
            echo "status=failed" >> $GITHUB_OUTPUT
            echo "Exit code: $exit_code"
            echo "=== Combined log ==="
            head -n 50 "${{ matrix.issue_number }}.log" || echo "No log found"
            exit $exit_code
          fi
          
          
      - name: Create summary
        if: always()
        run: |
          echo "## Issue #${{ matrix.issue_number }}" >> $GITHUB_STEP_SUMMARY
          echo "- Repository: ${{ matrix.repo_url }}" >> $GITHUB_STEP_SUMMARY
          echo "- Status: ${{ steps.process.outputs.status }}" >> $GITHUB_STEP_SUMMARY
          if [ -n "${{ steps.process.outputs.package_name }}" ]; then
            echo "- Package name: ${{ steps.process.outputs.package_name }}" >> $GITHUB_STEP_SUMMARY
          fi
          if [ -f "${{ matrix.issue_number }}.log" ]; then
            echo "- Log size: $(wc -c < ${{ matrix.issue_number }}.log) bytes" >> $GITHUB_STEP_SUMMARY
          fi
          if [ -d "output/${{ steps.process.outputs.package_name }}/package.nix" ]; then
            echo "- Generated package.nix: ✓" >> $GITHUB_STEP_SUMMARY
          fi
          if [ -f "${{ matrix.issue_number }}.log" ] && [ -s "${{ matrix.issue_number }}.log" ]; then
            echo "### Log excerpt:" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            tail -n 50 "${{ matrix.issue_number }}.log" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi

  aggregate-results:
    needs: build-test-packages
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Aggregate results
        run: |
          echo "# Test Package Build Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Build jobs completed. Individual job summaries contain detailed results." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Check individual job logs and summaries for packaging details." >> $GITHUB_STEP_SUMMARY
