name: Build Test Packages

on:
  workflow_dispatch:
    inputs:
      max_packages:
        description: 'Maximum number of packages to build (0 for all)'
        required: false
        default: '5'
        type: number
      model_provider:
        description: 'Model provider to use'
        required: false
        default: 'anthropic'
        type: choice
        options:
          - anthropic
          - ollama
      model:
        description: 'Model to use (e.g., claude-3-5-haiku-20241022 or ollama/qwen2.5-coder)'
        required: false
        default: 'claude-3-5-haiku-20241022'
        type: string
      ollama_host:
        description: 'Ollama host URL (e.g., http://your-host.tailnet:11434)'
        required: false
        default: 'https://hydralisk.van-duck.ts.net:11435'
        type: string
  push:
    branches:
      - main
    paths:
      - 'research/packaging_requests/used_during_implementation.csv'
      - 'src/**'
      - '.github/workflows/train-on-dataset.yml'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Nix
        uses: cachix/install-nix-action@v24
        
      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: vibenix
          authToken: '${{ secrets.CACHIX_TOKEN }}'
        
      - name: Build packagerix environment
        run: |
          nix develop .# --command echo "Development environment ready"
        
      - name: Create matrix from CSV
        id: create-matrix
        run: |
          python3 -c "
          import csv
          import json
          
          matrix_data = []
          with open('research/packaging_requests/used_during_implementation.csv', 'r') as f:
              reader = csv.DictReader(f)
              for row in reader:
                  if row['repo_url']:  # Skip entries without repo URLs
                      clean_name = row['repo_url'].replace('https://github.com/', '')
                      matrix_data.append({
                          'issue_number': row['issue_number'],
                          'repo_url': row['repo_url'],
                          'repo_name': clean_name
                      })
          
          # GitHub Actions has a matrix size limit, so we might need to batch
          max_packages = int('${{ github.event.inputs.max_packages || 5 }}')
          if max_packages == 0:
              matrix = {'include': matrix_data}
          else:
              matrix = {'include': matrix_data[:max_packages]}
          
          with open('matrix.json', 'w') as f:
              json.dump(matrix, f)
          
          # Set output for GitHub Actions
          print(f'matrix={json.dumps(matrix)}')
          "
          echo "matrix=$(cat matrix.json)" >> $GITHUB_OUTPUT

  build-test-packages:
    needs: setup
    runs-on: ubuntu-latest
    name: Package ${{ matrix.repo_name }}
    timeout-minutes: 60
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
      max-parallel: 2  # Run 2 jobs in parallel to avoid API rate limits
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Nix
        uses: cachix/install-nix-action@v24
        
      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: vibenix
          authToken: '${{ secrets.CACHIX_TOKEN }}'
        
      - name: Tailscale
        if: ${{ github.event.inputs.model_provider == 'ollama' }}
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:oauth-client-gh-action-hydralisk-ollama
          
      - name: Create packagerix config
        run: |
          mkdir -p ~/.packagerix
          cat > ~/.packagerix/config.json << EOF
          {
            "provider": "${{ github.event.inputs.model_provider }}",
            "model": "${{ github.event.inputs.model }}",
            "backend": "litellm",
            "ollama_host": "${{ github.event.inputs.ollama_host }}"
          }
          EOF
          
      - name: Setup environment
        run: |
          # Set Anthropic API key as environment variable
          echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" >> $GITHUB_ENV
      
      - name: Process package request
        id: process
        run: |
          echo "Processing issue #${{ matrix.issue_number }} - ${{ matrix.repo_url }}"
          
          # Set default status
          echo "status=failed" >> $GITHUB_OUTPUT
          
          # Create output directory for this run
          mkdir -p output
          
          # Run packagerix with raw output and save results
          set -o pipefail
          nix develop .# -c python -m packagerix \
            --raw \
            --output-dir output \
            "${{ matrix.repo_url }}" \
            2>&1 | tee "${{ matrix.issue_number }}.log"
          exit_code=$?
          
          # Check if the command succeeded
          if [ $exit_code -eq 0 ]; then
            echo "status=success" >> $GITHUB_OUTPUT
            # Find the package name from the output directory
            if [ -d output ]; then
              package_name=$(ls output | head -n1)
              if [ -n "$package_name" ]; then
                echo "package_name=$package_name" >> $GITHUB_OUTPUT
              fi
            fi
          else
            echo "status=failed" >> $GITHUB_OUTPUT
            echo "Exit code: $exit_code"
            echo "=== Combined log ==="
            head -n 50 "${{ matrix.issue_number }}.log" || echo "No log found"
          fi
          
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: packagerix-output-${{ matrix.issue_number }}
          path: |
            ${{ matrix.issue_number }}.log
            output/
            ~/.packagerix/config.json
          retention-days: 1
          
      - name: Create summary
        if: always()
        run: |
          echo "## Issue #${{ matrix.issue_number }}" >> $GITHUB_STEP_SUMMARY
          echo "- Repository: ${{ matrix.repo_url }}" >> $GITHUB_STEP_SUMMARY
          echo "- Provider: ${{ github.event.inputs.model_provider }}" >> $GITHUB_STEP_SUMMARY
          echo "- Model: ${{ github.event.inputs.model }}" >> $GITHUB_STEP_SUMMARY
          echo "- Status: ${{ steps.process.outputs.status }}" >> $GITHUB_STEP_SUMMARY
          if [ -n "${{ steps.process.outputs.package_name }}" ]; then
            echo "- Package name: ${{ steps.process.outputs.package_name }}" >> $GITHUB_STEP_SUMMARY
          fi
          if [ -f "${{ matrix.issue_number }}.log" ]; then
            echo "- Log size: $(wc -c < ${{ matrix.issue_number }}.log) bytes" >> $GITHUB_STEP_SUMMARY
          fi
          if [ -d "output/${{ steps.process.outputs.package_name }}/package.nix" ]; then
            echo "- Generated package.nix: ✓" >> $GITHUB_STEP_SUMMARY
          fi
          if [ -f "${{ matrix.issue_number }}.log" ] && [ -s "${{ matrix.issue_number }}.log" ]; then
            echo "### Log excerpt:" >> $GITHUB_STEP_SUMMARY
            echo '<pre>' >> $GITHUB_STEP_SUMMARY
            tail -n 50 "${{ matrix.issue_number }}.log" >> $GITHUB_STEP_SUMMARY
            echo '</pre>' >> $GITHUB_STEP_SUMMARY
          fi
          
      - name: Fail job if packaging failed
        if: always() && steps.process.outputs.status == 'failed'
        run: |
          echo "Packaging failed, failing the job"
          echo "Status was: ${{ steps.process.outputs.status }}"
          exit 1

  aggregate-results:
    needs: build-test-packages
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: packagerix-output-*
          
      - name: Aggregate results
        run: |
          echo "# Test Package Build Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          total=0
          success=0
          failed=0
          
          for dir in artifacts/packagerix-output-*; do
            if [ -d "$dir" ]; then
              issue_num=$(basename "$dir" | sed 's/packagerix-output-//')
              total=$((total + 1))
              
              # Check if there's a package.nix file in the output directory
              if [ -n "$(find "$dir/output" -name "package.nix" 2>/dev/null)" ]; then
                success=$((success + 1))
              else
                failed=$((failed + 1))
              fi
            fi
          done
          
          echo "- Total processed: $total" >> $GITHUB_STEP_SUMMARY
          echo "- Successful: $success" >> $GITHUB_STEP_SUMMARY
          echo "- Failed: $failed" >> $GITHUB_STEP_SUMMARY
          
      - name: Create combined artifact
        run: |
          mkdir -p combined-results
          if [ -d artifacts ] && [ "$(ls -A artifacts)" ]; then
            cp -r artifacts/* combined-results/
          else
            echo "No artifacts found to combine"
            echo "No successful packages were built" > combined-results/README.txt
          fi
          
      - name: Upload combined results
        uses: actions/upload-artifact@v4
        with:
          name: all-test-results
          path: combined-results/
          retention-days: 90
