name: Build Test Packages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'research/packaging_requests/used_during_implementation.csv'
      - 'src/**'
      - '.github/workflows/train-on-dataset.yml'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Nix
        uses: cachix/install-nix-action@v24
        
      - name: Build packagerix
        run: |
          # Build packagerix development environment
          nix develop .# --command echo "Development environment ready"
          
      - name: Cache packagerix config
        run: |
          # Create config directory
          mkdir -p ~/.packagerix
          
          # Create model configuration file
          cat > ~/.packagerix/config.json << EOF
          {
            "provider": "anthropic",
            "model": "claude-3-5-haiku-20241022",
            "backend": "litellm"
          }
          EOF
          
      - name: Upload packagerix config
        uses: actions/upload-artifact@v4
        with:
          name: packagerix-config
          path: ~/.packagerix/
          retention-days: 1
        
      - name: Create matrix from CSV
        id: create-matrix
        run: |
          python3 -c "
          import csv
          import json
          
          matrix_data = []
          with open('research/packaging_requests/used_during_implementation.csv', 'r') as f:
              reader = csv.DictReader(f)
              for row in reader:
                  if row['repo_url']:  # Skip entries without repo URLs
                      matrix_data.append({
                          'issue_number': row['issue_number'],
                          'repo_url': row['repo_url']
                      })
          
          # GitHub Actions has a matrix size limit, so we might need to batch
          # Limit to first 5 entries for testing
          matrix = {'include': matrix_data[:5]}
          
          with open('matrix.json', 'w') as f:
              json.dump(matrix, f)
          
          # Set output for GitHub Actions
          print(f'matrix={json.dumps(matrix)}')
          "
          echo "matrix=$(cat matrix.json)" >> $GITHUB_OUTPUT

  build-test-packages:
    needs: setup
    runs-on: ubuntu-latest
    name: Package ${{ matrix.repo_url }}
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
      max-parallel: 5  # Limit concurrent jobs to avoid rate limiting
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Nix
        uses: cachix/install-nix-action@v24
        
      - name: Download packagerix config
        uses: actions/download-artifact@v4
        with:
          name: packagerix-config
          path: ~/
          
      - name: Setup environment
        run: |
          # Set Anthropic API key as environment variable
          # (packagerix will pick it up from env vars as fallback)
          echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" >> $GITHUB_ENV
      
      - name: Process package request
        id: process
        run: |
          echo "Processing issue #${{ matrix.issue_number }} - ${{ matrix.repo_url }}"
          
          # Create output directory for this run
          mkdir -p output
          
          # Run packagerix with raw output and save results
          { nix develop .# -c python -m packagerix \
              --raw \
              --output-dir output \
              "${{ matrix.repo_url }}" \
              2>&1 | tee "${{ matrix.issue_number }}.log"; } \
            && exit_code=0 || exit_code=$?
          
          # Check if the command succeeded
          if [ $exit_code -eq 0 ]; then
            echo "status=success" >> $GITHUB_OUTPUT
            # Find the package name from the output directory
            if [ -d output ]; then
              package_name=$(ls output | head -n1)
              if [ -n "$package_name" ]; then
                echo "package_name=$package_name" >> $GITHUB_OUTPUT
              fi
            fi
          else
            echo "status=failed" >> $GITHUB_OUTPUT
            echo "Exit code: $exit_code"
            echo "=== Combined log ==="
            head -n 50 "${{ matrix.issue_number }}.log" || echo "No log found"
          fi
          
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: packagerix-output-${{ matrix.issue_number }}
          path: |
            ${{ matrix.issue_number }}.log
            output/
          retention-days: 30
          
      - name: Create summary
        run: |
          echo "## Issue #${{ matrix.issue_number }}" >> $GITHUB_STEP_SUMMARY
          echo "- Repository: ${{ matrix.repo_url }}" >> $GITHUB_STEP_SUMMARY
          echo "- Status: ${{ steps.process.outputs.status }}" >> $GITHUB_STEP_SUMMARY
          if [ -n "${{ steps.process.outputs.package_name }}" ]; then
            echo "- Package name: ${{ steps.process.outputs.package_name }}" >> $GITHUB_STEP_SUMMARY
          fi
          if [ -f "${{ matrix.issue_number }}.log" ]; then
            echo "- Log size: $(wc -c < ${{ matrix.issue_number }}.log) bytes" >> $GITHUB_STEP_SUMMARY
          fi
          if [ -d "output/${{ steps.process.outputs.package_name }}/package.nix" ]; then
            echo "- Generated package.nix: ✓" >> $GITHUB_STEP_SUMMARY
          fi
          if [ -f "${{ matrix.issue_number }}.log" ] && [ -s "${{ matrix.issue_number }}.log" ]; then
            echo "### Log excerpt:" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            tail -n 50 "${{ matrix.issue_number }}.log" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi

  aggregate-results:
    needs: build-test-packages
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: packagerix-output-*
          
      - name: Aggregate results
        run: |
          echo "# Test Package Build Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          total=0
          success=0
          failed=0
          
          for dir in artifacts/packagerix-output-*; do
            if [ -d "$dir" ]; then
              issue_num=$(basename "$dir" | sed 's/packagerix-output-//')
              total=$((total + 1))
              
              # Check if there's a package.nix file in the output directory
              if [ -n "$(find "$dir/output" -name "package.nix" 2>/dev/null)" ]; then
                success=$((success + 1))
              else
                failed=$((failed + 1))
              fi
            fi
          done
          
          echo "- Total processed: $total" >> $GITHUB_STEP_SUMMARY
          echo "- Successful: $success" >> $GITHUB_STEP_SUMMARY
          echo "- Failed: $failed" >> $GITHUB_STEP_SUMMARY
          
      - name: Create combined artifact
        run: |
          mkdir -p combined-results
          if [ -d artifacts ] && [ "$(ls -A artifacts)" ]; then
            cp -r artifacts/* combined-results/
          else
            echo "No artifacts found to combine"
            echo "No successful packages were built" > combined-results/README.txt
          fi
          
      - name: Upload combined results
        uses: actions/upload-artifact@v4
        with:
          name: all-test-results
          path: combined-results/
          retention-days: 90
